/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Calendar: typeof import('./src/components/calendar.vue')['default']
    CalendarIndex: typeof import('./src/components/Calendar-index.vue')['default']
    copy: typeof import('./src/components/Calendar-index copy.vue')['default']
    'Data.index': typeof import('./src/components/data.index.vue')['default']
    DataIndex: typeof import('./src/components/Data-Index.vue')['default']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
