/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CalendarIndex: typeof import('./src/components/Calendar-index.vue')['default']
    FakeHeader: typeof import('./src/components/Fake-Header.vue')['default']
    MessageBox: typeof import('./src/components/Message-Box.vue')['default']
    MsgBox: typeof import('./src/components/msg-box.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideComponents: typeof import('./src/components/Side-components.vue')['default']
  }
}
