<script setup>
import { useComStore } from '@/stores'
const useCom = useComStore()
</script>
<template>
  <loading
    v-model:active="useCom.isLoading"
    :can-cancel="true"
    :lock-scroll="true"
    opacity="1"
    transition="custom-fade"
    ><div class="loadingio-spinner-spin-2abhr8xqxe5">
      <div class="ldio-xvqhmi1gwv">
        <div><div></div></div>
        <div><div></div></div>
        <div><div></div></div>
        <div><div></div></div>
        <div><div></div></div>
        <div><div></div></div>
        <div><div></div></div>
        <div><div></div></div>
      </div>
    </div>
  </loading>
</template>

<style type="text/css">
@keyframes custom-fade {
  0% {
    opacity: 0;
  }
  50% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.custom-fade-enter-active {
  animation: custom-fade 1s;
}
.custom-fade-leave-active {
  opacity: 0;
}
@keyframes ldio-6bb837a511t {
  0% {
    opacity: 1;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1.5, 1.5);
  }
  100% {
    opacity: 0;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1, 1);
  }
}
@keyframes ldio-xvqhmi1gwv {
  0% {
    opacity: 1;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1.5, 1.5);
  }
  100% {
    opacity: 0;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1, 1);
  }
}
.ldio-xvqhmi1gwv div > div {
  position: absolute;
  width: 12px;
  height: 12px;
  border-radius: 50%;
  background: #1d3f72;
  animation: ldio-xvqhmi1gwv 1s linear infinite;
}
.ldio-xvqhmi1gwv div:nth-child(1) > div {
  left: 74px;
  top: 44px;
  animation-delay: -0.875s;
}
.ldio-xvqhmi1gwv > div:nth-child(1) {
  transform: rotate(0deg);
  transform-origin: 80px 50px;
}
.ldio-xvqhmi1gwv div:nth-child(2) > div {
  left: 65px;
  top: 65px;
  animation-delay: -0.75s;
}
.ldio-xvqhmi1gwv > div:nth-child(2) {
  transform: rotate(45deg);
  transform-origin: 71px 71px;
}
.ldio-xvqhmi1gwv div:nth-child(3) > div {
  left: 44px;
  top: 74px;
  animation-delay: -0.625s;
}
.ldio-xvqhmi1gwv > div:nth-child(3) {
  transform: rotate(90deg);
  transform-origin: 50px 80px;
}
.ldio-xvqhmi1gwv div:nth-child(4) > div {
  left: 23px;
  top: 65px;
  animation-delay: -0.5s;
}
.ldio-xvqhmi1gwv > div:nth-child(4) {
  transform: rotate(135deg);
  transform-origin: 29px 71px;
}
.ldio-xvqhmi1gwv div:nth-child(5) > div {
  left: 14px;
  top: 44px;
  animation-delay: -0.375s;
}
.ldio-xvqhmi1gwv > div:nth-child(5) {
  transform: rotate(180deg);
  transform-origin: 20px 50px;
}
.ldio-xvqhmi1gwv div:nth-child(6) > div {
  left: 23px;
  top: 23px;
  animation-delay: -0.25s;
}
.ldio-xvqhmi1gwv > div:nth-child(6) {
  transform: rotate(225deg);
  transform-origin: 29px 29px;
}
.ldio-xvqhmi1gwv div:nth-child(7) > div {
  left: 44px;
  top: 14px;
  animation-delay: -0.125s;
}
.ldio-xvqhmi1gwv > div:nth-child(7) {
  transform: rotate(270deg);
  transform-origin: 50px 20px;
}
.ldio-xvqhmi1gwv div:nth-child(8) > div {
  left: 65px;
  top: 23px;
  animation-delay: 0s;
}
.ldio-xvqhmi1gwv > div:nth-child(8) {
  transform: rotate(315deg);
  transform-origin: 71px 29px;
}
.loadingio-spinner-spin-2abhr8xqxe5 {
  width: 90px;
  height: 90px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-xvqhmi1gwv {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.9);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-xvqhmi1gwv div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
